# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/admin/Desktop/lab9_3/lab8_1.cache/wt [current_project]
set_property parent.project_path C:/Users/admin/Desktop/lab9_3/lab8_1.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files -quiet c:/Users/admin/Desktop/lab9_3/lab8_1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp
set_property used_in_implementation false [get_files c:/Users/admin/Desktop/lab9_3/lab8_1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp]
add_files -quiet c:/Users/admin/Desktop/lab9_3/lab8_1.srcs/sources_1/ip/c_counter_binary_2/c_counter_binary_2.dcp
set_property used_in_implementation false [get_files c:/Users/admin/Desktop/lab9_3/lab8_1.srcs/sources_1/ip/c_counter_binary_2/c_counter_binary_2.dcp]
add_files -quiet c:/Users/admin/Desktop/lab9_3/lab8_1.srcs/sources_1/ip/c_counter_binary_3/c_counter_binary_3.dcp
set_property used_in_implementation false [get_files c:/Users/admin/Desktop/lab9_3/lab8_1.srcs/sources_1/ip/c_counter_binary_3/c_counter_binary_3.dcp]
add_files -quiet c:/Users/admin/Desktop/lab9_3/lab8_1.srcs/sources_1/ip/c_counter_binary_4/c_counter_binary_4.dcp
set_property used_in_implementation false [get_files c:/Users/admin/Desktop/lab9_3/lab8_1.srcs/sources_1/ip/c_counter_binary_4/c_counter_binary_4.dcp]
add_files -quiet c:/Users/admin/Desktop/lab9_3/lab8_1.srcs/sources_1/ip/c_counter_binary_5/c_counter_binary_5.dcp
set_property used_in_implementation false [get_files c:/Users/admin/Desktop/lab9_3/lab8_1.srcs/sources_1/ip/c_counter_binary_5/c_counter_binary_5.dcp]
read_verilog -library xil_defaultlib C:/Users/admin/Desktop/lab9_3/lab8_1.srcs/sources_1/new/lab8_2.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/admin/Desktop/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files C:/Users/admin/Desktop/Nexys4DDR_Master.xdc]


synth_design -top lab8_2 -part xc7a100tcsg324-1


write_checkpoint -force -noxdef lab8_2.dcp

catch { report_utilization -file lab8_2_utilization_synth.rpt -pb lab8_2_utilization_synth.pb }
